movies/urls.py
from django.conf.urls import url, patterns, include

from movies import views

urlpatterns = [
    url(r'^$', views.index_test, name='IndexTest'),
    url(r'signup/$', views.user_sign_up, name='UserSignUp'),
    url(r'signin/$', views.sign_in, name='signin'),
    url(r'signout/$', views.sign_out, name='signout'),
    url(r'movie_list/$', views.pagination, name='MovieList'),
    # url(r'movie_list/$', views.movie_list, name='MovieList'),
    url(r'^movie_summary/(\w+)/$', views.movie_summary, name='MovieSummary'),
    url(r'search/$', views.search, name='Search'),
    url(r'^add_to_library/(\w+)/$', views.add_to_library, name='add_to_library'),
    url(r'^remove_from_library/(\w+)/$', views.remove_from_library, name='remove_from_library'),
    # url(r'test403/$', views.test403, name='test403'),
]

xmdb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('movies.urls', namespace='movies')),
    url(r'^admin/', include(admin.site.urls)),
# FIXME What is this? This shouldn't be necessary... --fixed
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Director(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name

class Writer(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name

class Actor(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name

# class User(User):
#     def __str__(self):
#         return self.username

class Movie(models.Model):
    name = models.TextField()
    year = models.IntegerField()
    director = models.ForeignKey(Director, null=True, blank=True)
    writer = models.ForeignKey(Writer, null=True, blank=True)
    actors = models.ManyToManyField(Actor, blank=True)
    RATED = (
        (1, 'G'),
        (2, 'PG'),
        (3, 'PG-13'),
        (4, 'R')
    )
    rated = models.IntegerField(choices=RATED, null=True, blank=True)
    #thumbnail = models.ImageField(upload_to="movie_thumbnails", null=True, blank=True)
    poster = models.TextField(null=True)
    imdbId = models.TextField(null=True)
    users = models.ManyToManyField(User)

    def __str__(self):
        return "%s (%d)" % (self.name, int(self.year))

    # def __unicode__(self):
    #     return self.name

movies/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.views import generic
from django.contrib.auth.models import User
from movies.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
import requests
from django import forms, views
from django.contrib.auth.forms import UserCreationForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import pdb
# Create your views here.

# FIXME Regarding naming conventions, best to follow pep-8. --fixed
# methods should be lower case and words separated by underscores
# Classes can be first letter capitalized (not camel case), no underscores

def index_test(request):
    return render(request, 'movies/index.html')

def sign_in(request):
    # FIXME What if user is already logged in?  -- fixed
    if request.method == 'POST':
        un = request.POST.get('username')
        pw = request.POST.get('password')
        user = authenticate(username=un, password=pw)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('movies:IndexTest'))
            else:
                return HttpResponseRedirect("Your account is disabled.")
        else:
            #print('Invalid login details: {0}, {1}'.format(un, pw))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'movies/signin.html', {})

def user_sign_up(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("")
        else:
            form = UserCreationForm()
    return render(request, "movies/index.html")

def movie_summary(request, movie_id, search_query=None):

    if not request.user.is_authenticated or request.user.is_anonymous:
        movielist = Movie.objects.all()
    else:
        movielist = request.user.movie_set.all()
    try:
        m = movielist.get(imdbId=movie_id)
    except Movie.DoesNotExist:
        r = requests.get('http://www.omdbapi.com/?i={0}&plot=short&r=json'.format(movie_id))
        imdb = r.json().get('imdbID')
        # pdb.set_trace()
        themoviedb = requests.get('http://api.themoviedb.org/3/movie/{0}?external_source=imdb_id/images&api_key=a922b176fe232a0599b7a991011c6dd6'.format(imdb))
        themoviedb.encoding = 'ISO-8859-1'
        poster_url = themoviedb.json().get('poster_path')
        poster_url = poster_url[1:]
        d = Director.objects.get_or_create(name=r.json().get('Director'))[0]
        w = Writer.objects.get_or_create(name=r.json().get('Writer'))[0]
        stars = r.json().get('Actors').split(', ')
        alist = []
        for a in stars:
            if a not in Actor.objects.all():
                actor = Actor.objects.get_or_create(name=a)[0]
                alist.append(actor)
                actor.save()

        j = r.json()

        if j.get('Rated') == 'G':
            rated = 1
        elif j.get('Rated') == 'PG':
            rated = 2
        elif j.get('Rated') == 'PG-13':
            rated = 3
        else:
            rated = 4

        new_movie = Movie.objects.get_or_create(name=r.json().get('Title'), year=r.json().get('Year'),
                                         director=d, writer=w, rated=rated, imdbId=r.json().get('imdbID'))[0]

        new_movie.poster = 'http://image.tmdb.org/t/p/w300/{0}'.format(poster_url)
        template_poster = 'http://image.tmdb.org/t/p/w300/{0}'.format(poster_url)
        r.json()[template_poster] = template_poster
        new_movie.save()
        for a in alist:
            new_movie.actors.add(a)
        new_movie.save()
        if search_query is not None:
            r = requests.get('http://www.omdbapi.com/?t={0}&y=&plot=short&r=json'.format(search_query.replace(' ', '+')))
        else:
            r = requests.get('http://www.omdbapi.com/?i={0}&plot=short&r=json'.format(imdb))
        return render(request, 'movies/movie_summary.html', {'movie': r.json, 'poster': template_poster, 'exists_in_library': False})

    r = requests.get('http://www.omdbapi.com/?t={0}&y=&plot=short&r=json'.format(m.name.replace(' ', '+')))

    try:
        if request.user.is_authenticated and request.user.is_active:
            exists_in_library = request.user.movie_set.get(name=r.json().get('Title')).name

        else:
            exists_in_library = False

    except Movie.DoesNotExist:
        exists_in_library = False

    return render(request, 'movies/movie_summary.html', {'movie': r.json, 'poster': m.poster, 'exists_in_library': exists_in_library})

def search(request):
    search_query = request.POST.get('search_query')

    r = requests.get('http://www.omdbapi.com/?t={0}&y=&plot=short&r=json'.format(search_query.replace(' ', '+')))

    try:
        exists_in_library = Movie.objects.get(name=r.json().get('Title')).name
    except Movie.DoesNotExist:
        exists_in_library = False
    if r.json().get('Response') == 'True':
        return movie_summary(request, r.json().get('imdbID'), search_query)
    else:
        return render(request, 'movies/index.html', {'SearchError': 'Movie not found!'})

def add_to_library(request, id):
    # FIXME Grab any extra fields we will need in the future and save
    # so we don't have to make extra requests
    m = Movie.objects.get(imdbId=id)

    if request.user not in m.users.all():
        m.users.add(request.user)
    m.save()

    return redirect('/movie_list')

def remove_from_library(request, id):
    removeme = request.user.movie_set.get(imdbId=id)
    request.user.movie_set.remove(removeme)

    return redirect('/movie_list')

def sign_out(request):
    logout(request)
    return redirect('/')

@login_required
def pagination(request):
    movie_list = themovies = request.user.movie_set.all()
    paginator = Paginator(movie_list, 10)

    page = request.GET.get('page')
    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        movies = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        movies = paginator.page(paginator.num_pages)

    for movie in themovies:
        r = requests.get('http://www.omdbapi.com/?t={0}&y=&plot=short&r=json'.format(movie.name.replace(' ', '+')))
        # movie.poster = r.json().get('Poster')
        movie.imdbId = r.json().get('imdbID')
        movie.save()

    return render_to_response('movies/movie_list.html', {"movies": movies})

# def test403(request):
#     r = requests.get('http://www.omdbapi.com/?t=Cars&y=&plot=short&r=json')
#     return render_to_response('movies/test403.html', {'json': r.json()})

templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.1/bootstrap-table.min.css">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>XMDB</title>

    <!-- Custom CSS -->
    <link href="/static/css/agency.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% load staticfiles %}

    <style>
        body {
            background-attachment: fixed;
            /* fix this later!!!
            background-image: url(../../static/img/header-bg.jpg);
            /* above was ../static/img/header-bg.jpg */
            background-image: url({% static "img/header-bg.jpg" %});
            background-position: center center;
            background-repeat: none;
            font-family: "Roboto Slab","Helvetica Neue",Helvetica,Arial,sans-serif;
            padding-top: 5%;
        }

        th, h1, h2, h3, h4, h5, h6 {
            color: #ffffff;
        }

        input {
            color: #fed136;
        }

        td {
            color: #ffffff;
            width: 13%;
        }
    </style>
</head>
<body>
    <div>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header page-scroll">
                    <a class="navbar-brand page-scroll" href="/">XMDB</a>
                </div>
            </div>
        </nav>
    </div>

    <div class="container">
        {% block content %}
            This is the body.
        {% endblock %}
    </div>

        <script src="/static/js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="/static/js/bootstrap.min.js"></script>

        <!-- Plugin JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
        <script src="/static/js/classie.js"></script>
        <script src="/static/js/cbpAnimatedHeader.js"></script>


        <!-- Custom Theme JavaScript -->
        <script src="/static/js/agency.js"></script>
</body>
</html>

templates/movies/index.html
<!DOCTYPE html>
<html lang="en">
{% comment %} 
  FIXME make better use of the base template 
{% endcomment %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>XMDB</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-table.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/agency.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">XMDB</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    {% if not user.is_authenticated %}
                        <li>
                            <a class="page-scroll" href="#search">Search</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="{% url 'movies:signin' %}" >Sign In</a>
                        </li>
                    {% else %}
                        <li>
                        <a class="page-scroll" href="movie_list">My Library</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="#search">Search</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="{% url 'movies:signout' %}" >Sign Out</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <header>
        <div class="container">
            <div class="intro-text">
                {% if not user.is_authenticated %}
                    <div class="intro-lead-in">Welcome To Excella Movie Database!</div>
                    <div class="intro-heading"></div>
                    <a href="#signup" class="page-scroll btn btn-xl">Sign up</a>
                {% else %}
                    <div class="intro-lead-in">Hi {{user}}! Feel free to search below</div>
                {% endif %}
            </div>
        </div>
    </header>

    <section id="search">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Search</h2>
                </div>
            </div>
        </div>
        <div class="container" style= "width:33%;">
            <form action="{% url 'movies:Search' %}" method="post" class="">
                {% csrf_token %}
                <h4 style="color: red">{{ SearchError }}</h4>
                <input type="text" class="form-control" name="search_query" id ="search_query" placeholder="Search a movie title" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit">Go</button>
            </form>
        </div>
    </section>

    {% if not user.is_authenticated %}
        <section id="signup">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2 class="section-heading">Sign up</h2>
                        <h3 class="section-subheading text-muted">Create your account:</h3>
                    </div>
                </div>
            </div>
            <div class="container" style= "width:33%;">
                <form action="{% url 'movies:UserSignUp' %}" method="post" class="">
                    {% csrf_token %}
                    {{ ErrorMessage }}
                    <input type="text" class="form-control" name="username" id ="username" placeholder="Enter Desired Username" required>
                    <input type="text" class="form-control" name="email" id ="email" placeholder="Email" required>
                    <input type="password" class="form-control" name="password1" id="password1" placeholder="Password" required>
                    <input type="password" class="form-control" name="password2" id = "password2" placeholder="Confirm Password" required>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">
                        Sign up</button>
                    <a href="http://www.reactionface.info/sites/default/files/images/1287666826226.png" class="pull-right need-help">Need help? </a><span class="clearfix"></span>
                </form>
            </div>
        </section>
    {% endif %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Excella Consulting 2015</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="https://twitter.com/ExcellaCo"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="https://www.facebook.com/excellaconsulting"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="https://www.linkedin.com/company/excella-consulting"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="/static/js/classie.js"></script>
    <script src="/static/js/cbpAnimatedHeader.js"></script>
    <script src="/static/js/bootstrap-table.js"></script>


    <!-- Custom Theme JavaScript -->
    <script src="/static/js/agency.js"></script>

</body>

</html>

templates/movies/movie_list.html
<!DOCTYPE html>
<html lang="en">

{% extends 'movies/base.html' %}

{% block content %}

    <body>
        <div class="container">
                <table class="table table-striped" >
                    <thead>
                        <th>Movie</th>
                        <th></th>
                        <th>Year</th>
                        <th>Director</th>
                        <th>Writer</th>
                        <th>Actors</th>
                        <th>Rating</th>
                    </thead>
                    {% for movie in movies %}
                        <tr style= "background-color: transparent">
                            <!--<td><img src="{{ MEDIA_URL }}{{ movie.thumbnail }}"/></td>-->
                            <td><img width="80%" height="40%" src="{{ movie.poster }}"/></td>
                            <td style="vertical-align: middle; text-align: left"><a style="color:#ffffff; font-weight: bold; text-decoration: none" href="/movie_summary/{{ movie.imdbId }}">{{movie.name}}</a></td>
                            <td style="vertical-align: middle; text-align: left">{{movie.year}}</td>
                            <td style="vertical-align: middle; text-align: left">{{movie.director}}</td>
                            <td style="vertical-align: middle; text-align: left">{{movie.writer}}</td>
                            <td style="vertical-align: middle; text-align: left">
                                    {%  for actor in movie.actors.all %}
                                        <div>{{actor}}</div>
                                    {% endfor %}
                            </td>
                            <td style="vertical-align: middle; text-align: left;">{{movie.get_rated_display}}</td>
                        </tr>
                    {% endfor %}
                </table>
        </div>

        <div class="pagination">
        <span class="step-links">
            {% if movies.has_previous %}
                <a href="?page={{ movies.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current" style="color: white">
                Page {{ movies.number }} of {{ movies.paginator.num_pages }}.
            </span>

            {% if movies.has_next %}
                <a href="?page={{ movies.next_page_number }}">next</a>
            {% endif %}
        </span>
</div>

    </body>

{% endblock content %}

templates/movies/movie_summary.html
<!DOCTYPE html>
<html lang="en">

{% extends 'movies/base.html' %}

{% block content %}

    <body>
        <div class="row">
            <div style="padding-top: 2%;" class="hidden-xs col-sm-5 col-md-4">
                <img src="{{ poster }}"/>
            </div>
            <div class="col-sm-7 col-md-8">
                <div>
                <h2>{{ movie.Title }} ({{ movie.Year }})</h2>
                <h5>{{ movie.Rated }} | {{ movie.Runtime }} | {{ movie.Genre }} | {{ movie.Released }} ({{ movie.Country }})</h5>
                </div>
                <div style="padding-top: 1%">
                    <h4>Average Rating: {{ movie.imdbRating }} from {{ movie.imdbVotes }} viewers</h4>
                </div>
                <div style="padding-top: 1%">
                    <h4>{{ movie.Plot }}</h4>
                </div>
                <div style="padding-top: 1%">
                    {% if movie.Director == movie.Writer %}
                        <h4>Written and Directed By: {{ movie.Director }}</h4>
                    {% else %}
                        <div style="padding-top: 1%">
                            <h4>Director: {{ movie.Director }}</h4>
                        </div>
                        <div style="padding-top: 1%">
                            <h4>Writer: {{ movie.Writer }}</h4>
                        </div>
                    {% endif %}
                </div>
                <div style="padding-top: 1%">
                    <h4>Stars: {{ movie.Actors }}</h4>
                </div>
                <div style="padding-top: 1%">
                    <h4>Awards: {{ movie.Awards }}</h4>
                </div>
                {% if user.is_authenticated %}
                    {% if exists_in_library == False %}
                        <div style="padding-top: 3%">
                            <button onclick="window.location='/add_to_library/{{ movie.imdbID }}'" class="page-scroll btn btn-xl">Add to my library</button>
                        </div>
                    {% else %}
                        <div style="padding-top: 3%">
                            <button onclick="window.location='/remove_from_library/{{ movie.imdbID }}'" class="page-scroll btn btn-xl">Remove from my library</button>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </body>

{% endblock content %}

templates/movies/signin.html
<!DOCTYPE html>
<html lang="en">

{% extends 'movies/base.html' %}
{% load staticfiles %}

{% block content %}

<body>
    <!-- Navigation -->


    <div class="container" style="padding-left: 0%; padding-top: 15%">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-md-offset-4">
                <h1 class="text-center login-title">Sign in to XMDB</h1>
                <div class="account-wall">
                    <form action = "{% url 'movies:signin' %}" method="post" class="form-signin">
                        {% csrf_token %}
                        <label>{{ UsernameErrorMessage }} {{ PasswordErrorMessage }}</label>
                    <input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
                    <input type="password" name="password" class="form-control" placeholder="Password" required>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">
                        Sign in</button>
                    <label class="checkbox pull-left">
                        <input type="checkbox" value="remember-me">
                        <p style="color: #fed136">Remember me</p>
                    </label>
                    <a href="/signup" class="pull-right need-help">Create an account</a><span class="clearfix"></span>
                    </form>
                </div>

            </div>
        </div>
    </div>
</body>

{% endblock content %}

templates/movies/test403.html
<!DOCTYPE html>
<html lang="en">

<head>

</head>

<body>
    {{ json }}
</body>

</html>